# Generated by Django 5.2.1 on 2025-08-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtimer', '0002_alter_solve_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='averageFive',
            field=models.CharField(max_length=64),
        ),
    ]
